
services: 
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
    
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5100:5432
    environment:
      POSTGRES_PASSWORD: sql
      
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - 5341:80
    volumes:
      - seq-data:/data
      - seq-logs:/dev/log
    environment:
      ACCEPT_EULA: Y
        
volumes: 
  rabbitmqdata:
  seq-data:
  seq-logs: