
services: 
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
    
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5100:5432
    environment:
      POSTGRES_PASSWORD: sql
        
volumes: 
  rabbitmqdata: